### ISSUE TITLE
Unexpected value AnimatesDirective

### ISSUE THREAD

**Issue by egeneral** [fabiandev/css-animator#11]
Using Angular-cli, when I try to build for production, the following error pops up..

`ERROR in Unexpected value 'AnimatesDirective in app.module.ts`
`Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'`

**Comment by fabiandev** [comment]
I haven't tested this package with the angular-cli yet. Also, did you have a look at https://github.com/angular/angular-cli/issues/4551 and https://github.com/angular/angular-cli/issues/5596?
 
With the given error I cannot really say if css-animator causes it, or if it's something else. Probably you can post your `app.module.ts`, so I can have a look.

**Comment by fabiandev** [comment]
I just checked https://angular.io/docs/ts/latest/cookbook/aot-compiler.html and it seems this package is not AoT compliant. I will push an update asap, in the meantime you can use it without ahead of time compilation. I'll keep you posted.

**Comment by fabiandev** [comment]
Just in case, please post you `app.module.ts` anyway.

**Comment by egeneral** [comment]
Hi, 

Here's a snippet of my module file.

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AnimatesDirective, AnimationService } from 'css-animator';
import { MaterializeModule } from 'angular2-materialize';

import { AnswerDirective } from './directives/answer.directive';
import {
    .
    .
    NotificationComponent
} from './components';

import {
    .
    .
    LocalizationService
} from './services';

@NgModule({
    imports: [
        CommonModule,
        MaterializeModule
    ],
    declarations: [
        .
        .
        AnimatesDirective,
        AnswerDirective,
        NotificationComponent
    ],
    providers: [
        .
        .
        LocalizationService
    ]
})
export class TesterModule {
}`

```

**Comment by fabiandev** [comment]
I've finally added support for AOT compilation with Angular as of `v2.1.0` of this package.

When you upgrade to the latest version of css-animator, please make sure to just import `AnimatorModule` and that you don't add `AnimatesDirective` to the declarations, or `AnimationService` to the providers of your module. It should look similar to the code below.

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { AnimatorModule } from 'css-animator';

@NgModule({
  imports: [
    BrowserModule,
    AnimatorModule
  ],
  declarations: [
    AppComponent
  ],
  bootstrap: [
    AppComponent
  ],
})
export class AppModule { }
```

**Comment by egeneral** [comment]
awesome! much appreciated.
