### ISSUE TITLE
Animation done more than once on iOS safari

### ISSUE THREAD

**Issue by kingDevGit** [fabiandev/css-animator#14]
I set the animation to animate only once but it animates twice on IOS 9.2 .  Chrome fine.

**Comment by fabiandev** [comment]
Can you please provide a live example, e.g. on [jsbin.com](https://jsbin.com/?js,console)?

**Comment by kingDevGit** [comment]
In fact it seems the common css animation flicker problem on iOS. I tried adding -webkit-backface-visibility: hidden but no luck.

**Comment by fabiandev** [comment]
If you provide a code example, I could check if this issue is related to `css-animator`.
