### ISSUE TITLE
Some animations do not work properly

### ISSUE THREAD

**Issue by erperejildo** [fabiandev/css-animator#17]
The point is that when I call some animations (couldn't try with all of them) I face some issues: the html content does like a jump, executes de animation and comes back to his first position.

Let say about `tada` animation (https://daneden.github.io/animate.css/). It moves like 5px down when it's animating and it comes up 5px back again.

I was inspecting how works `animate.css` on previous link and I realised that it applies 2 classes: `animated` and `tada`.

The only different here using `css-animator` (as you will know) is that it adds `animated`, `tada` and `animated-show` (nothing happens adding manually this class to my html) BUT also all of this style directly to the html:
`style="visibility: visible; position: absolute; top: 0px; left: 0px; width: 201px; height: 39px; margin: 0px; animation-fill-mode: none; animation-timing-function: ease; animation-play-state: running; animation-direction: normal; animation-duration: 1000ms; animation-iteration-count: 1;"`

So the problem here comes with this:
```
position: absolute;  
top: 0px; 
left: 0px; 
width: 201px; 
height: 39px; 
margin: 0px; 
```
So why we need this code for?

If I add these 2 classes (`animated` and `tada`) directly to my element it does the animation properly so that's why I know is not either `animate.css` or my html/css problem.

Trying with Chrome

**Comment by fabiandev** [comment]
Please make yourself familiar with the [options](https://github.com/fabiandev/css-animator#options) of this package, as well as how it works in general.
`css-animator` does try to pin the element to its current position while animating. By default it uses absolute positioning, which can be changed to fixed, via the `fixed` option. Also, if you don't want to pin the element, there's also an option for that, named `pin`. Furthermore, if you want to keep the space of an element occupied even when it is hidden, take a look at the `useVisibility` option.

**Comment by erperejildo** [comment]
So I added this: `this.animator.pin = false;`

No it doesn't move, but it does like a flash at beginning of the animation, moving the rest of the content to the top and down again.

As I can see it's not adding any position absolute:
`style="animation-fill-mode: none; animation-timing-function: ease; animation-play-state: running; animation-direction: normal; animation-duration: 1000ms; animation-iteration-count: 1;"`

If I add this previous style and the 2 classes manually on the html it works properly, but not running the animation on the controller.

Also, why is not `pin: false` as default?

**Comment by fabiandev** [comment]
If you can provide a minimal working example I can have a look. There are various things that may cause unexpected behavior, including the CSS rules of the element itself or its container.

**Comment by erperejildo** [comment]
https://github.com/erperejildo/temporary
Open mobile landscape view on Chrome. Do the operation and you'll see 3 different animations. Click again on right corner button to see text animation

**Comment by fabiandev** [comment]
Your repo is missing files in `src/providers`. However, with some modifications I could build your project and I don't see any real issues with `pin` set to `false`.

If you were addressing the short blinking before "Congratulations" animates, this is because you were using `.show()` instead of `.animate()`.

It should look something like this:

```ts
this.animator.setType('tada').animate(this.congratsDOM.nativeElement);
```

When using `show` or `hide`, this library makes sure that the element is hidden or visible, respectively, before applying the animation. When changing line `205` and `231` of `src/pages/sums/game/game.ts` to use `animate()`, there is no more blinking.

**Comment by erperejildo** [comment]
Hmmm, I see. I thought that `.show` was exactly the same to `.animate` with the only difference that .show forces that element to be displayed on the html.

When I click on `playAgain()` I apply `zoomOut`. Why is moving to the right? On that case is ok if I use `.hide` right?

**Comment by fabiandev** [comment]
`.show()` ensures that the element is hidden before the animation is applied, `.hide()` makes sure that the element is visible before animating, and `.animate()` applies the animation without changing its visibility.

In the case of `zoomOut` the `.hide()` method is appropriate. The animation itself is provided by [animate.css](https://github.com/daneden/animate.css), and it seems the `transform` CSS rule on `.sum-ok` is affecting the anchor point of the animation.

I did a quick test and replaced `transform` for the following:

```css
margin-top: -64px;
margin-left: -106px;
```

This causes the zoom animation to be centered, but please note that the numbers are not 100% accurate and may change if the container dimensions change. You may want to look into a better way to center your element.

**Comment by erperejildo** [comment]
Unfortunately I can't change the `transform` and use those values because otherwise wouldn't be responsive. 

Ok, I'll give it a workaround. At least the other one is working one, which is more important.

Thanks!
