### ISSUE TITLE
Disable animations

### ISSUE THREAD

**Issue by erperejildo** [fabiandev/css-animator#24]
This is not an issue, just a question.

I've got this option in my app:
![captura](https://user-images.githubusercontent.com/5629919/33804299-df05a9e8-dd99-11e7-9ecf-5c1a29454cd8.JPG)

Is there any option to disable animations? The only thing I found is this way:   `this.animator.setDuration(0);`
but I'm already changing duration in some places so I'd have to double check this parameter many times.

How can I archive this?

**Comment by fabiandev** [comment]
There is currently no way to disable animations with this package. Setting the animation duration to zero still performs a number of things and I wouldn't recommend to use it as a workaround and you should probably take care of this on your own. However, I'm considering to add this feature in a future release.

**Comment by erperejildo** [comment]
Great!
Let me know when then

**Comment by erperejildo** [comment]
Perfect, works like a charm!

**Comment by fabiandev** [comment]
This feature is now published as of `v2.3.0` at `css-animator@latest`.

**Comment by erperejildo** [comment]
With hidden element using `.show` instead `.animate` the element pops up with some delay. Would be possible to display it as soon the page loads?
Might be a bit tricky if as long we are using `hidden`, which is an Angular property right?

**Comment by fabiandev** [comment]
I will have a look asap. `hidden` actually is a native HTML attribute. If you can track down what's causing the delay in the meantime, a PR is also very welcome.

**Comment by erperejildo** [comment]
That's what I mean... I think is not gonna be possible to fix this flicker if we use `hidden`.
When the page finishes loading there is some time till our code gets triggered. Let's say that we have a quite of few images to display and we want to animate the first one. This would be the best example.

I think there is no way to fix this unless we use a specific attribute for our tags.

But tbh this is not critical at all. We have to understand that this is a specific mode to make old phones faster. I rather prefer this flicker than no option to disable animations

**Comment by fabiandev** [comment]
When does this flicker occur? Do you mean that the element is visible on page load even though it should be hidden (i.e., has the `hidden` attribute)? In this case, try adding the following to your CSS rules if you haven't already:

```css
[hidden] {
  display: none;
}
```

**Comment by erperejildo** [comment]
No, the element is hidden because we're using a native attribute. Once our code gets triggered with `.show()` we displayed it without animation (because it's disabled).
So since it's loading till we animate it takes some milliseconds
