### ISSUE TITLE
ngRepeat animation (feature)

### ISSUE THREAD

**Issue by erperejildo** [fabiandev/css-animator#25]
Is there any possible way to animate the elements that we are adding on a ngRepeat?

I found 2 ways:
A) Adding the classes directly on the tag with the ngRepeat. This is the easiest one but not really functional because we will animate it every time we come back to this view and we have no control over this
B) Adding hidden on the ngRepeat and every time we add one element we add a .show() but doesn't work properly. Maybe because sometimes the animation goes faster than the html and the content doesn't exist yet.

I was thinking on a tag property because this should be managed from the html if I'm not wrong.

**Comment by fabiandev** [comment]
Did you try with the [directive](../#angular-directive) provided by `css-animator`?

**Comment by erperejildo** [comment]
Oh that's perfect, thanks for pointing me out!

What about to removing the element? It works fine when I add it but not when I remove it.
Maybe using a event different to `animatesOnInit` right?

**Comment by fabiandev** [comment]
I have just added `[animatesOnDestroy]` and `animatesDestroyMode` on the directive, and published `v2.3.0-beta.4` via `css-animator@next`. I didn't have time to test - can you try if this works?

**Comment by fabiandev** [comment]
When thinking about it, i tend to say this won't work, as Angular will remove the DOM element before the animation can finish, as the animation builder uses asynchronous code.

**Comment by fabiandev** [comment]
Are you on `css-animator@next` for testing this? I might have to look into this again, however, I just started working on the next major version, where this feature may be implemented.

**Comment by erperejildo** [comment]
Hmmm, maybe I wasn't. I installed that version but maybe without @next. But anyway, there is no rush... Even less if you are working on this.

I also found that Ionic has some style issues when you try to animate an `ion-list` element with below elements.
 
Just give me a shout when you have this implemented on latest version and I'll do some testing with Ionic-mobile.
