### ISSUE TITLE
Animate hidden element (SPA)

### ISSUE THREAD

**Issue by erperejildo** [fabiandev/css-animator#26]
When we want to go back one page in Ionic we can use either `pop()` or `dismiss()`. We have this previous page already loaded as a SPA app but I'm facing an issue with `.show()`.
First time it's ok because the element is hidden in our template so we execute this `.show()` and we display it as normally, but when we go back to this page again the element is already displayed and we hide and show it again.

Is there any way to fix this or this is a similar issue like the one I commented here?:
https://github.com/fabiandev/css-animator/issues/24#issuecomment-361079569

**Comment by fabiandev** [comment]
Are you using the directive or are you triggering the animation from the component‘s class for this specific case?

**Comment by erperejildo** [comment]
I'm using the animation on my component's class. I can easily hide the element when I leave that page and it would work but didn't know if we had a specific method/directive already for this

**Comment by erperejildo** [comment]
Cool, I'll do that then
