### ISSUE TITLE
css-animator is not working in IE 11..

### ISSUE THREAD

**Issue by ashish-786** [fabiandev/css-animator#28]
css-animator is not working in IE 11. No animations are working also page load animation also not working. and no errors are logging in console. Please help

**Comment by fabiandev** [comment]
Sorry, I totally missed this issue. You may need to include polyfills for e.g. `Object.assign` and other things that IE 11 does not support.

**Comment by fabiandev** [comment]
Closing stale issue, feel free to open a new issue, thanks 🙌
