### ISSUE TITLE
library (css-animator) which declares AnimatorModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy.

### ISSUE THREAD

**Issue by anuj141samariya** [fabiandev/css-animator#34]
Please resolve this issue
as i am able to run my application but i have to put this option as false in tsconfig.app.json
"angularCompilerOptions": {
    "enableIvy": false
  }
so how i will run this with the ivy compiler

**Comment by fabiandev** [comment]
Can you please share a repo with steps to reproduce?

**Comment by anuj141samariya** [comment]
HI
I am not able to share the repo as it is not allowed by my organization,
But i am using css-animator in one of my component , when i am using with angular 8 it is working fine but i am not able to use it with angular 9 and angular 10 with the ivy compiler , somethiing goes wrong with the AnimatorModule which is not compile by ngcc compiler , can you look into that , it will be great help of yours.

**Comment by anuj141samariya** [comment]
For steps to reproduce , 
1) just import the
import { AnimationService, AnimatorModule } from 'css-animator' in my module,
providers: [AnimationService] and imports: [AnimatorModule] in ngmodule

and in the component
2) import { AnimationBuilder, AnimationService } from 'css-animator';
    and make a variable  public animator: AnimationBuilder; public animators: AnimationBuilder

3) and use the classes in one of my function like animation = 'zoomOut' like this

This whole code is working with angular 8 but when we move this whole thing to angular 9 and angular 10 then
at the compilation time i will get the error 

**library (css-animator) which declares AnimatorModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy**

**Comment by anuj141samariya** [comment]
@fabiandev 
Hi
Can you please look into the issue

**Comment by fabiandev** [comment]
I will look into the issue as soon as possible, please give me another week or two.

**Comment by fabiandev** [comment]
In the meantime, please setup a repo which can be cloned to reproduce the issue @anuj141samariya

**Comment by anuj141samariya** [comment]
@fabiandev hi
have you look into that,
It will be great help of yours , if you look into that

**Comment by fabiandev** [comment]
This project is set up with `ngc` not `ngcc`. Please provide a minimal project setup in a repository where this is reproducible out of the box and I will have a look. Thanks.

**Comment by anuj141samariya** [comment]
@fabiandev i will set up the project you can look

**Comment by saikiranvadlakonda** [comment]
Hi All,

Any solution around this issue. Please let me know.

Thanks.

**Comment by fabiandev** [comment]
As mentioned `css-animator` is not setup for `ngcc`. Please provide a project setup to reproduce the behavior – I can look into extending support from there.  PRs are very welcome, too :)

**Comment by fabiandev** [comment]
@anuj141samariya @saikiranvadlakonda I've put out a beta which should resolve the issue, see https://github.com/fabiandev/css-animator/issues/31#issuecomment-899801438. Stay tuned!

**Comment by fabiandev** [comment]
Fixed via `v2.4.0`, please re-open if you are still experiencing issues 🙌
