### ISSUE TITLE
I'm having trouble with the css-animator being unable to be loaded

### ISSUE THREAD

**Issue by ThomasCorbin** [fabiandev/css-animator#5]
When I try to use it as a service, I get something like this:

Error loading http://localhost:4200/css-animator as "css-animator" from http://localhost:4200/app/wizard-step/wizard-step.component.js

I'm using the following:
import { AnimationService, AnimationBuilder } from 'css-animator';

I used this:
npm install --save css-animator animate.css

I'm using angular2 rc4

Thanks - this is such a great idea, the css-animator

**Comment by ThomasCorbin** [comment]
I didn't add an entry to system-config.ts

**Comment by fabiandev** [comment]
Sorry that I didn't respond to your issue, but I'm glad you could solve it :)
