### ISSUE TITLE
Staggering support

### ISSUE THREAD

**Issue by jtushar53** [fabiandev/css-animator#6]
staggering effect for *ngFor like this would have been great 

https://plnkr.co/edit/NgwMMSILAxRuxkOBGyzi?p=preview

**Comment by fabiandev** [comment]
Yes, would be something nice to have. I added it to the list for #3 (v1.3 roadmap). I don't have a lot of time right now but I hope to make some progress on it soon.

**Comment by fabiandev** [comment]
I decided not to add support for specific things like Angular's *ngFor, as this library's intent is to be a helper for css animations for any JavaScript application.
Anyway, using the simple directive provided by `css-animator` could help to achieve this (e.g. using `[animatesOnInit]` alongside `animatesInitMode="show"`). It would also be possible to chain the promise returned by the `AnimationBuilder`, to start an animation once another one has finished.
The next version and an updated documentation of this package will be published soon. In the meantime it can be installed via the next tag: `yarn add css-animator@next`.
