### ISSUE TITLE
Security Risk ElementRef

### ISSUE THREAD

**Issue by nevyen** [fabiandev/css-animator#7]
Hey,
first thanks for this nice tool. I started to use it and it works great.

But as I looked around I have a look at the angular docs and found that ElementRef could be a security risk. https://angular.io/docs/ts/latest/api/core/index/ElementRef-class.html

They suggest to use their Render which is at EXPERIMENTAL state at the moment. 

No the question is: Is it possible to use your tool with the renderer? Or are their no security risks if you only use ElementRef for animation?

**Comment by fabiandev** [comment]
Hi! Glad you like it :)

Generally, I do have to make direct manipulations to the DOM, as the package is written for any JavaScript application. It just can also be used with Angular. I included a basic service and directive, to make it easier to use it with Angular 2 out of the box.

But I do see your concern and I will implement security measures, like sanitizing values, to eliminate any possibilities of XSS attacks and I will also look into the experimental Renderer.

Thanks for flagging this!

**Comment by fabiandev** [comment]
The next version (can currently be installed via the next tag: `yarn add css-animator@next`) doesn't take inputs from the html element directly, so we should be safe here.
Using Angular's renderer wasn't really an option, as the core should also be usable without Angular 2, mentioned in my previous comment.
