### ISSUE TITLE
Add an Angular2 demo

### ISSUE THREAD

**Issue by hevan** [fabiandev/css-animator#8]
please add a demo, we can refer.

Directive
<div animates #animation="animates">
<span (click)="animation.start({type: 'bounce'})">Click me!</span>
</div>

ERROR!

'{ selector: string; styles: any[]; templateUrl: string; directives: typeof AnimatesDirective[]; }'

**Comment by lukemcd** [comment]
+1
A simple demo would really help here.

**Comment by AleksandarAleksandrov** [comment]
+1

**Comment by fabiandev** [comment]
Okay guys, I'll add a demo asap.

**Comment by hevan** [comment]
good work，thanks！

**Comment by fabiandev** [comment]
I'll reopen this issue and will close it once I've added a demo.

**Comment by fabiandev** [comment]
I'm working on a simple demo and an improved version.
In the meantime you may want to check [angular2-quiz-app](https://github.com/fabiandev/angular2-quiz-app), where I'm using css-animator with Angular2.

**Comment by fabiandev** [comment]
I've done some work on this package and a new version will be released soon.
It's already in the master and you can install it via the next tag: `yarn add css-animator@next`

Also I've created a very basic example for the next version, which you can look up in the [`docs/`](https://github.com/fabiandev/css-animator/tree/master/docs) folder of this repository. It's also hosted on GitHub Pages: https://fabiandev.github.io/css-animator/

The [angular2-quiz-app](https://github.com/fabiandev/angular2-quiz-app) repo is also already using `css-animator@next`.

I think the `next` tag will be released as `v1.3` or `v2.0` and I'd appreciate any feedback.
The API hasn't really changed, but some things behave a bit differently, so it's more likely I'll go for `v2`.

**Comment by fabiandev** [comment]
Version [2.0.1](https://github.com/fabiandev/css-animator/releases/tag/v2.0.1) has been released. The demo and documentation has been updated as well.
